name: Catacombs
main: net.steeleyes.catacombs.Catacombs
version: 2.1
depend:
softdepend: [Permissions, PermissionsEx, PermissionsBukkit, Vault]
commands:
    catacombs:
        description: Build catacombs
        aliases: ['cat']
